spring.application.name=EmployeeManagementSystem

#database details
spring.datasource.url=jdbc:mysql://localhost:3306/EmployeeDB
spring.datasource.username=root
# Set MYSQL_PASSWORD as an environment variable (or in your IDE run config)
#spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.password=@Manasi1125
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
